[package]
name = "yammer"
version = "0.15.0"
authors = ["Robert Escriva <robert@rescrv.net>"]
edition = "2021"
description = "yammer provides an ollama-compatible client library."
license = "Apache-2.0"
repository = "https://github.com/rescrv/yammer"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
getopts = "0.2"
reqwest = { version = "0.12", features = ["json"] }
rustyline = { version = "15", features = ["derive"] }
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.40", features = ["rt", "rt-multi-thread", "macros"] }

arrrg = "0.7"
arrrg_derive = "0.7"
minimal_signals = "0.4"
shvar = "0.5"
utf8path = "0.6"
libc = "0.2"
yammer-derive = { "path" = "derive", version = "0.2.0" }
